### ISSUE TITLE
Can't authenticate account that uses Google Login 2FA

### ISSUE THREAD

**Issue by mckernanin** [Airmail/Todoist-AMPlug#2]
I can't find a way to login to my todoist account which is linked to my gmail address with 2FA enabled. I've tried an app password in the plugin, and that doesn't work either. I can get my API key manually, but the plugin doesn't allow just pasting it in.

**Comment by xpil** [comment]
I am having the same problem. I can use Todoist via the web interface, but the local app freezes during the 2FA step.
